name: Wowza Streaming Engine Trial
services:
    trial:
        hostname: wse.docker
        image: wowza/wowza-streaming-engine:latest-trial
        platform: linux/amd64
        env_file: .env
        environment:
            - WSE_LICENSE_KEY=$WSE_LICENSE_KEY
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - IPWHITELIST=*
            - TRANSCODER=enabled #enabled | disabled | remove to not change
            - LOG_LEVEL=INFO #DEBUG INFO WARN ERROR
            - SIMU_LIVE=disabled
        volumes:
#to persist the configurations between starts of Wowza Streaming Engine, uncomment the lines below:
#            - ./wse/applications:/usr/local/WowzaStreamingEngine/applications
#            - ./wse/conf:/usr/local/WowzaStreamingEngine/conf
#            - ./wse/content:/usr/local/WowzaStreamingEngine/content
#            - ./wse/transcoder:/usr/local/WowzaStreamingEngine/transcoder
            - ./conf:/usr/local/WowzaStreamingEngine/conf.addon
            - ./build/libs:/usr/local/WowzaStreamingEngine/lib.addon
            - ./src/main/resources/transcoder:/usr/local/WowzaStreamingEngine/transcoder.addon
        ports:
            - 8087:8087
            - 80:80
            - 443:443
            - 1935:1935

    whisper_server:
        hostname: whisper.server
        image: wowza/whipser_streaming:1.0.0
        #platform: linux/arm64
        environment:
            - MODEL=tiny.en # tiny.en, base.en, small.en, medium.en, large-v3
            - LOG_LEVEL=INFO
            - MIN_CHUNK_SIZE=1
        ports:
            - 3000:3000
        volumes:
            - ./model_cache:/tmp

    manager:
        hostname: wsem.docker
        image: wowza/wowza-streaming-engine-manager:latest
        environment:
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
        ports:
            - 8088:8080
